import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Slider } from "@/components/ui/slider";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from "@/components/ui/card";
import { InfoCircledIcon } from "@radix-ui/react-icons";
import { DollarSign, PieChart, ArrowRight } from "lucide-react";

interface RevenueShareFormProps {
  revenueSharing: {
    investorPercentage: string;
    founderPercentage: string;
    description: string;
  };
  onChange: (data: {
    investorPercentage: string;
    founderPercentage: string;
    description: string;
  }) => void;
}

export default function RevenueShareForm({ revenueSharing, onChange }: RevenueShareFormProps) {
  const [investorPercentage, setInvestorPercentage] = useState(
    parseInt(revenueSharing.investorPercentage) || 50
  );
  const [description, setDescription] = useState(revenueSharing.description || "");

  // Update founder percentage automatically
  const founderPercentage = 100 - investorPercentage;

  // Update parent component when values change
  useEffect(() => {
    onChange({
      investorPercentage: investorPercentage.toString(),
      founderPercentage: founderPercentage.toString(),
      description
    });
  }, [investorPercentage, founderPercentage, description, onChange]);

  // Handle slider change
  const handleSliderChange = (value: number[]) => {
    setInvestorPercentage(value[0]);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="space-y-8"
    >
      <div className="glass rounded-xl border border-white/10 p-6">
        <h3 className="text-xl font-medium mb-6">Revenue Sharing Model</h3>
        
        <div className="space-y-6">
          <p className="text-gray-300">
            Define how project revenue will be shared between investors and founders. 
            This determines what percentage of revenue generated by the project will be 
            distributed to investors.
          </p>
          
          <div className="bg-black/30 rounded-lg border border-white/10 p-4 space-y-4">
            <div className="flex justify-between items-center">
              <h4 className="font-medium">Revenue Distribution</h4>
              <div className="flex items-center gap-2 text-sm">
                <InfoCircledIcon className="h-4 w-4 text-gray-400" />
                <span className="text-gray-400">Adjust the slider to set percentages</span>
              </div>
            </div>
            
            <div className="space-y-6 pt-4">
              <div className="space-y-2">
                <div className="flex justify-between">
                  <Label>Investor Share</Label>
                  <span className="font-medium text-primary">{investorPercentage}%</span>
                </div>
                <Slider
                  value={[investorPercentage]}
                  min={0}
                  max={100}
                  step={1}
                  onValueChange={handleSliderChange}
                  className="py-4"
                />
              </div>
              
              <div className="space-y-2">
                <div className="flex justify-between">
                  <Label>Founder Share</Label>
                  <span className="font-medium text-orange-400">{founderPercentage}%</span>
                </div>
                <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-orange-400/70" 
                    style={{ width: `${founderPercentage}%` }}
                  ></div>
                </div>
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-6">
              <div className="bg-black/40 rounded-lg border border-white/5 p-4 flex items-start gap-3">
                <div className="bg-primary/10 p-2 rounded-lg mt-1">
                  <DollarSign className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h5 className="font-medium">Investor Revenue</h5>
                  <p className="text-sm text-gray-400 mt-1">
                    {investorPercentage}% of project revenue will be distributed to investors 
                    proportional to their investment amount.
                  </p>
                </div>
              </div>
              
              <div className="bg-black/40 rounded-lg border border-white/5 p-4 flex items-start gap-3">
                <div className="bg-orange-400/10 p-2 rounded-lg mt-1">
                  <PieChart className="h-5 w-5 text-orange-400" />
                </div>
                <div>
                  <h5 className="font-medium">Founder Revenue</h5>
                  <p className="text-sm text-gray-400 mt-1">
                    {founderPercentage}% of project revenue will be retained by the project founders 
                    for operations and growth.
                  </p>
                </div>
              </div>
            </div>
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="revenueDescription">Revenue Sharing Description (Optional)</Label>
            <Textarea
              id="revenueDescription"
              placeholder="Describe your revenue sharing model in more detail, including any conditions or milestones that may affect the distribution..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="bg-black/30 border-white/10 min-h-[100px]"
            />
          </div>
        </div>
      </div>
      
      <div className="space-y-4">
        <h3 className="text-xl font-medium">Revenue Sharing Examples</h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card className="bg-black/30 border-white/10">
            <CardHeader className="pb-2">
              <CardTitle className="text-base">SaaS Subscription Model</CardTitle>
              <CardDescription>Monthly revenue distribution</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-400">Monthly Revenue</span>
                  <span>$10,000</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="h-3 w-3 text-gray-500" />
                  <span className="text-gray-400">Investor Share (50%)</span>
                  <span className="ml-auto">$5,000</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="h-3 w-3 text-gray-500" />
                  <span className="text-gray-400">Founder Share (50%)</span>
                  <span className="ml-auto">$5,000</span>
                </div>
              </div>
            </CardContent>
          </Card>
          
          <Card className="bg-black/30 border-white/10">
            <CardHeader className="pb-2">
              <CardTitle className="text-base">Transaction Fee Model</CardTitle>
              <CardDescription>Per-transaction distribution</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-400">Transaction Fee</span>
                  <span>2% of volume</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="h-3 w-3 text-gray-500" />
                  <span className="text-gray-400">Investor Share (30%)</span>
                  <span className="ml-auto">0.6% of volume</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="h-3 w-3 text-gray-500" />
                  <span className="text-gray-400">Founder Share (70%)</span>
                  <span className="ml-auto">1.4% of volume</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </motion.div>
  );
}
